// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: students.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_students_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_students_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Person.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_students_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_students_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_students_2eproto;
class ClassInfo;
struct ClassInfoDefaultTypeInternal;
extern ClassInfoDefaultTypeInternal _ClassInfo_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::ClassInfo* Arena::CreateMaybeMessage<::ClassInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class ClassInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ClassInfo) */ {
 public:
  inline ClassInfo() : ClassInfo(nullptr) {}
  ~ClassInfo() override;
  explicit PROTOBUF_CONSTEXPR ClassInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ClassInfo(const ClassInfo& from);
  ClassInfo(ClassInfo&& from) noexcept
    : ClassInfo() {
    *this = ::std::move(from);
  }

  inline ClassInfo& operator=(const ClassInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClassInfo& operator=(ClassInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ClassInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const ClassInfo* internal_default_instance() {
    return reinterpret_cast<const ClassInfo*>(
               &_ClassInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ClassInfo& a, ClassInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(ClassInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ClassInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ClassInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ClassInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ClassInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ClassInfo& from) {
    ClassInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ClassInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ClassInfo";
  }
  protected:
  explicit ClassInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStusFieldNumber = 2,
    kClassNoFieldNumber = 1,
  };
  // repeated .Person stus = 2;
  int stus_size() const;
  private:
  int _internal_stus_size() const;
  public:
  void clear_stus();
  ::Person* mutable_stus(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Person >*
      mutable_stus();
  private:
  const ::Person& _internal_stus(int index) const;
  ::Person* _internal_add_stus();
  public:
  const ::Person& stus(int index) const;
  ::Person* add_stus();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Person >&
      stus() const;

  // int32 class_no = 1;
  void clear_class_no();
  int32_t class_no() const;
  void set_class_no(int32_t value);
  private:
  int32_t _internal_class_no() const;
  void _internal_set_class_no(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:ClassInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Person > stus_;
    int32_t class_no_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_students_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ClassInfo

// int32 class_no = 1;
inline void ClassInfo::clear_class_no() {
  _impl_.class_no_ = 0;
}
inline int32_t ClassInfo::_internal_class_no() const {
  return _impl_.class_no_;
}
inline int32_t ClassInfo::class_no() const {
  // @@protoc_insertion_point(field_get:ClassInfo.class_no)
  return _internal_class_no();
}
inline void ClassInfo::_internal_set_class_no(int32_t value) {
  
  _impl_.class_no_ = value;
}
inline void ClassInfo::set_class_no(int32_t value) {
  _internal_set_class_no(value);
  // @@protoc_insertion_point(field_set:ClassInfo.class_no)
}

// repeated .Person stus = 2;
inline int ClassInfo::_internal_stus_size() const {
  return _impl_.stus_.size();
}
inline int ClassInfo::stus_size() const {
  return _internal_stus_size();
}
inline ::Person* ClassInfo::mutable_stus(int index) {
  // @@protoc_insertion_point(field_mutable:ClassInfo.stus)
  return _impl_.stus_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Person >*
ClassInfo::mutable_stus() {
  // @@protoc_insertion_point(field_mutable_list:ClassInfo.stus)
  return &_impl_.stus_;
}
inline const ::Person& ClassInfo::_internal_stus(int index) const {
  return _impl_.stus_.Get(index);
}
inline const ::Person& ClassInfo::stus(int index) const {
  // @@protoc_insertion_point(field_get:ClassInfo.stus)
  return _internal_stus(index);
}
inline ::Person* ClassInfo::_internal_add_stus() {
  return _impl_.stus_.Add();
}
inline ::Person* ClassInfo::add_stus() {
  ::Person* _add = _internal_add_stus();
  // @@protoc_insertion_point(field_add:ClassInfo.stus)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Person >&
ClassInfo::stus() const {
  // @@protoc_insertion_point(field_list:ClassInfo.stus)
  return _impl_.stus_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_students_2eproto
