// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: students.proto

#include "students.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR ClassInfo::ClassInfo(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.stus_)*/{}
  , /*decltype(_impl_.class_no_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ClassInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ClassInfoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ClassInfoDefaultTypeInternal() {}
  union {
    ClassInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ClassInfoDefaultTypeInternal _ClassInfo_default_instance_;
static ::_pb::Metadata file_level_metadata_students_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_students_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_students_2eproto = nullptr;

const uint32_t TableStruct_students_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ClassInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ClassInfo, _impl_.class_no_),
  PROTOBUF_FIELD_OFFSET(::ClassInfo, _impl_.stus_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::ClassInfo)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_ClassInfo_default_instance_._instance,
};

const char descriptor_table_protodef_students_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016students.proto\032\014Person.proto\"4\n\tClassI"
  "nfo\022\020\n\010class_no\030\001 \001(\005\022\025\n\004stus\030\002 \003(\0132\007.Pe"
  "rsonb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_students_2eproto_deps[1] = {
  &::descriptor_table_Person_2eproto,
};
static ::_pbi::once_flag descriptor_table_students_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_students_2eproto = {
    false, false, 92, descriptor_table_protodef_students_2eproto,
    "students.proto",
    &descriptor_table_students_2eproto_once, descriptor_table_students_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_students_2eproto::offsets,
    file_level_metadata_students_2eproto, file_level_enum_descriptors_students_2eproto,
    file_level_service_descriptors_students_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_students_2eproto_getter() {
  return &descriptor_table_students_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_students_2eproto(&descriptor_table_students_2eproto);

// ===================================================================

class ClassInfo::_Internal {
 public:
};

void ClassInfo::clear_stus() {
  _impl_.stus_.Clear();
}
ClassInfo::ClassInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ClassInfo)
}
ClassInfo::ClassInfo(const ClassInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ClassInfo* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.stus_){from._impl_.stus_}
    , decltype(_impl_.class_no_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.class_no_ = from._impl_.class_no_;
  // @@protoc_insertion_point(copy_constructor:ClassInfo)
}

inline void ClassInfo::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.stus_){arena}
    , decltype(_impl_.class_no_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ClassInfo::~ClassInfo() {
  // @@protoc_insertion_point(destructor:ClassInfo)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ClassInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.stus_.~RepeatedPtrField();
}

void ClassInfo::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ClassInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:ClassInfo)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.stus_.Clear();
  _impl_.class_no_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ClassInfo::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 class_no = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.class_no_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .Person stus = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_stus(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ClassInfo::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ClassInfo)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 class_no = 1;
  if (this->_internal_class_no() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_class_no(), target);
  }

  // repeated .Person stus = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_stus_size()); i < n; i++) {
    const auto& repfield = this->_internal_stus(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ClassInfo)
  return target;
}

size_t ClassInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ClassInfo)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .Person stus = 2;
  total_size += 1UL * this->_internal_stus_size();
  for (const auto& msg : this->_impl_.stus_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // int32 class_no = 1;
  if (this->_internal_class_no() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_class_no());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ClassInfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ClassInfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ClassInfo::GetClassData() const { return &_class_data_; }


void ClassInfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ClassInfo*>(&to_msg);
  auto& from = static_cast<const ClassInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ClassInfo)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.stus_.MergeFrom(from._impl_.stus_);
  if (from._internal_class_no() != 0) {
    _this->_internal_set_class_no(from._internal_class_no());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ClassInfo::CopyFrom(const ClassInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ClassInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClassInfo::IsInitialized() const {
  return true;
}

void ClassInfo::InternalSwap(ClassInfo* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.stus_.InternalSwap(&other->_impl_.stus_);
  swap(_impl_.class_no_, other->_impl_.class_no_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ClassInfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_students_2eproto_getter, &descriptor_table_students_2eproto_once,
      file_level_metadata_students_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ClassInfo*
Arena::CreateMaybeMessage< ::ClassInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ClassInfo >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
